# Generated by Django 5.2 on 2025-05-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soko', '0002_category_product_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product/'),
        ),
    ]
